language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn jacoco:report coveralls:report -P travis
